import type { ConcernStatus } from "../types/dailyForm";

export function exportConcernTableAsImage(params: {
  orderNo: number;
  restaurantName: string;
  balanceDate: string;
  categories: string[];
  totalIngredients: number;
  items: {
    itemName: string;
    category: string;
    orderQty: number;
    status: ConcernStatus;
  }[];
}): void {
  const {
    orderNo,
    restaurantName,
    balanceDate,
    categories,
    totalIngredients,
    items,
  } = params;

  const dpr = window.devicePixelRatio || 1;
  const colWidths = [320, 120, 150];
  const tableWidth = colWidths.reduce((a, b) => a + b, 0);
  const padding = 24;
  const canvasWidth = tableWidth + padding * 2;

  const headerH = 120;
  const rowH = 40;
  const tableHeaderH = 38;
  const tableBodyH = items.length * rowH;
  const footerH = 32;
  const canvasHeight =
    headerH + tableHeaderH + tableBodyH + footerH + padding * 2;

  const canvas = document.createElement("canvas");
  canvas.width = canvasWidth * dpr;
  canvas.height = canvasHeight * dpr;
  canvas.style.width = `${canvasWidth}px`;
  canvas.style.height = `${canvasHeight}px`;

  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  ctx.scale(dpr, dpr);

  // Background
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, canvasWidth, canvasHeight);

  // Header block
  ctx.fillStyle = "#111827";
  ctx.fillRect(0, 0, canvasWidth, headerH);

  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 18px sans-serif";
  ctx.textAlign = "center";
  ctx.fillText("Shri Hoshnagi Enterprises", canvasWidth / 2, 32);

  ctx.font = "bold 14px sans-serif";
  ctx.fillStyle = "#f3f4f6";
  ctx.fillText(`Order #${orderNo}  ·  ${restaurantName}`, canvasWidth / 2, 56);

  ctx.font = "13px sans-serif";
  ctx.fillStyle = "#d1d5db";
  ctx.fillText(`Balance Date: ${balanceDate}`, canvasWidth / 2, 76);
  ctx.fillText(`Categories: ${categories.join(", ")}`, canvasWidth / 2, 94);
  ctx.fillText(`Total Ingredients: ${totalIngredients}`, canvasWidth / 2, 112);

  // Table header
  const tableStartY = headerH + padding;
  const tableX = padding;
  const colHeaders = ["Item Name", "Order Qty", "Status"];

  ctx.fillStyle = "#1f2937";
  ctx.fillRect(tableX, tableStartY, tableWidth, tableHeaderH);

  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 13px sans-serif";
  ctx.textAlign = "left";
  let cx = tableX;
  for (let i = 0; i < colHeaders.length; i++) {
    ctx.fillText(colHeaders[i], cx + 10, tableStartY + 24);
    cx += colWidths[i];
  }

  // Table rows
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const rowY = tableStartY + tableHeaderH + i * rowH;
    const isRejected = item.status === "rejected";

    // Row background
    ctx.fillStyle = i % 2 === 0 ? "#f9fafb" : "#ffffff";
    ctx.fillRect(tableX, rowY, tableWidth, rowH);

    // Row border
    ctx.strokeStyle = "#e5e7eb";
    ctx.lineWidth = 1;
    ctx.strokeRect(tableX, rowY, tableWidth, rowH);

    // Cell text
    ctx.textAlign = "left";
    const textY = rowY + rowH / 2 + 5;

    // Item Name
    ctx.fillStyle = isRejected ? "#ef4444" : "#111827";
    ctx.font = isRejected ? "13px sans-serif" : "bold 13px sans-serif";
    ctx.fillText(item.itemName, tableX + 10, textY);
    if (isRejected) {
      const textWidth = ctx.measureText(item.itemName).width;
      ctx.strokeStyle = "#ef4444";
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(tableX + 10, textY - 4);
      ctx.lineTo(tableX + 10 + textWidth, textY - 4);
      ctx.stroke();
    }

    // Order Qty
    ctx.fillStyle = isRejected ? "#ef4444" : "#374151";
    ctx.font = "13px sans-serif";
    const qtyStr = String(item.orderQty);
    ctx.fillText(qtyStr, tableX + colWidths[0] + 10, textY);
    if (isRejected) {
      const qtyWidth = ctx.measureText(qtyStr).width;
      ctx.strokeStyle = "#ef4444";
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(tableX + colWidths[0] + 10, textY - 4);
      ctx.lineTo(tableX + colWidths[0] + 10 + qtyWidth, textY - 4);
      ctx.stroke();
    }

    // Status
    const statusLabel =
      item.status === "accepted"
        ? "✅ Received"
        : item.status === "rejected"
          ? "❌ Not Received"
          : "—";
    ctx.fillStyle =
      item.status === "accepted"
        ? "#16a34a"
        : item.status === "rejected"
          ? "#dc2626"
          : "#9ca3af";
    ctx.font = "13px sans-serif";
    ctx.fillText(statusLabel, tableX + colWidths[0] + colWidths[1] + 10, textY);
  }

  // Outer border
  ctx.strokeStyle = "#d1d5db";
  ctx.lineWidth = 1;
  ctx.strokeRect(tableX, tableStartY, tableWidth, tableHeaderH + tableBodyH);

  // Footer
  ctx.fillStyle = "#6b7280";
  ctx.font = "11px sans-serif";
  ctx.textAlign = "center";
  ctx.fillText(
    `Generated by Shri Hoshnagi Enterprises · ${new Date().toLocaleString()}`,
    canvasWidth / 2,
    tableStartY + tableHeaderH + tableBodyH + 20,
  );

  canvas.toBlob((blob) => {
    if (!blob) return;
    const fileName = `order-${orderNo}-concern.png`;

    // Try Web Share API first (for WhatsApp etc.)
    if (
      navigator.share &&
      navigator.canShare &&
      navigator.canShare({
        files: [new File([blob], fileName, { type: "image/png" })],
      })
    ) {
      const file = new File([blob], fileName, { type: "image/png" });
      navigator
        .share({ files: [file], title: `Order #${orderNo} Concern Report` })
        .catch(() => {
          // Fall back to download
          downloadBlob(blob, fileName);
        });
    } else {
      downloadBlob(blob, fileName);
    }
  }, "image/png");
}

function downloadBlob(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
