/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryName = IDL.Text;
export const Ingredient = IDL.Record({
  'name' : IDL.Text,
  'category' : CategoryName,
});
export const Meal = IDL.Record({
  'name' : IDL.Text,
  'ingredients' : IDL.Vec(Ingredient),
});
export const Timestamp = IDL.Nat;
export const DailyRecordId = IDL.Nat;
export const Category = IDL.Record({ 'name' : CategoryName });
export const DailyRecord = IDL.Record({
  'meals' : IDL.Vec(Meal),
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  'addDailyRecord' : IDL.Func([IDL.Vec(Meal), Timestamp], [DailyRecordId], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllDailyRecords' : IDL.Func([], [IDL.Vec(DailyRecord)], ['query']),
  'getIngredientsByCategory' : IDL.Func(
      [CategoryName],
      [IDL.Vec(Ingredient)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryName = IDL.Text;
  const Ingredient = IDL.Record({
    'name' : IDL.Text,
    'category' : CategoryName,
  });
  const Meal = IDL.Record({
    'name' : IDL.Text,
    'ingredients' : IDL.Vec(Ingredient),
  });
  const Timestamp = IDL.Nat;
  const DailyRecordId = IDL.Nat;
  const Category = IDL.Record({ 'name' : CategoryName });
  const DailyRecord = IDL.Record({
    'meals' : IDL.Vec(Meal),
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    'addDailyRecord' : IDL.Func(
        [IDL.Vec(Meal), Timestamp],
        [DailyRecordId],
        [],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllDailyRecords' : IDL.Func([], [IDL.Vec(DailyRecord)], ['query']),
    'getIngredientsByCategory' : IDL.Func(
        [CategoryName],
        [IDL.Vec(Ingredient)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };