/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'name' : CategoryName }
export type CategoryName = string;
export interface DailyRecord {
  'meals' : Array<Meal>,
  'restaurantName' : string,
  'timestamp' : Timestamp,
}
export interface Ingredient { 'name' : string, 'category' : CategoryName }
export interface Meal { 'name' : string, 'ingredients' : Array<Ingredient> }
export type Timestamp = bigint;
export interface UserProfile { 'name' : string, 'restaurantName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDailyRecord' : ActorMethod<[Array<Meal>, Timestamp, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllDailyRecords' : ActorMethod<[], Array<DailyRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoriesByType' : ActorMethod<[string], Array<Category>>,
  'getIngredientsByCategory' : ActorMethod<[CategoryName], Array<Ingredient>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];