/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CategoryName = string;
export interface ConcernItemStatus {
  'status' : ConcernStatus,
  'receivedQty' : [] | [number],
  'itemName' : string,
  'orderQty' : number,
}
export interface ConcernRecord {
  'confirmedAt' : bigint,
  'confirmedBy' : string,
  'itemStatuses' : Array<ConcernItemStatus>,
  'orderId' : bigint,
  'restaurantName' : string,
}
export type ConcernStatus = { 'notReceived' : null } |
  { 'damage' : null } |
  { 'expired' : null } |
  { 'short' : null } |
  { 'spoiled' : null } |
  { 'received' : null };
export interface DailyRecord {
  'meals' : Array<Meal>,
  'restaurantName' : string,
  'timestamp' : Timestamp,
}
export interface Ingredient { 'name' : string, 'category' : CategoryName }
export interface MasterCategory { 'id' : string, 'name' : string }
export interface Meal { 'name' : string, 'ingredients' : Array<Ingredient> }
export interface RawMaterial {
  'id' : string,
  'name' : string,
  'category' : string,
}
export interface Restaurant { 'id' : string, 'name' : string }
export interface RestaurantAssignment {
  'allowedItems' : Array<string>,
  'allowedCategories' : Array<string>,
  'restaurantName' : string,
}
export interface RestaurantUser {
  'username' : string,
  'password' : string,
  'restaurantName' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addCategory' : ActorMethod<[string], undefined>,
  'addDailyRecord' : ActorMethod<[Array<Meal>, Timestamp, string], bigint>,
  'addRawMaterial' : ActorMethod<[string, string], undefined>,
  'addRestaurant' : ActorMethod<[string], undefined>,
  'addUser' : ActorMethod<[string, string, string], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteRawMaterial' : ActorMethod<[string], undefined>,
  'deleteRestaurant' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[string], undefined>,
  'getAllCategories' : ActorMethod<[], Array<{ 'name' : string }>>,
  /**
   * / Retrieve all stored concern records (for admin / reporting).
   */
  'getAllConcernRecords' : ActorMethod<[], Array<ConcernRecord>>,
  'getAllDailyRecords' : ActorMethod<[], Array<DailyRecord>>,
  'getCategories' : ActorMethod<[], Array<MasterCategory>>,
  /**
   * / Retrieve the confirmed concern record for a specific order, if any.
   */
  'getConcernRecord' : ActorMethod<[bigint, string], [] | [ConcernRecord]>,
  'getIngredientsByCategory' : ActorMethod<
    [string],
    Array<{ 'name' : string, 'category' : string }>
  >,
  'getRawMaterials' : ActorMethod<[], Array<RawMaterial>>,
  'getRawMaterialsByCategory' : ActorMethod<[string], Array<RawMaterial>>,
  'getRestaurantAssignment' : ActorMethod<
    [string],
    [] | [RestaurantAssignment]
  >,
  'getRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getUsers' : ActorMethod<[], Array<RestaurantUser>>,
  'resetToDefaultCredentials' : ActorMethod<[], undefined>,
  /**
   * / Save concern statuses for an order. Once saved, the record is permanently
   * / stored on-chain and visible to all users. Subsequent calls for the same
   * / (orderId, restaurantName) are silently ignored to enforce immutability.
   */
  'saveConcernRecord' : ActorMethod<
    [bigint, string, Array<ConcernItemStatus>, string],
    undefined
  >,
  'seedDefaultData' : ActorMethod<[], undefined>,
  'setAdminPassword' : ActorMethod<[string], undefined>,
  'setRestaurantAssignment' : ActorMethod<
    [string, Array<string>, Array<string>],
    undefined
  >,
  'updateCategory' : ActorMethod<[string, string], undefined>,
  'updateRawMaterial' : ActorMethod<[string, string, string], undefined>,
  'updateRestaurant' : ActorMethod<[string, string], undefined>,
  'updateUser' : ActorMethod<[string, string, string], undefined>,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
  'verifyUserLogin' : ActorMethod<[string, string], [] | [string]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];