/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryName = IDL.Text;
export const Ingredient = IDL.Record({
  'name' : IDL.Text,
  'category' : CategoryName,
});
export const Meal = IDL.Record({
  'name' : IDL.Text,
  'ingredients' : IDL.Vec(Ingredient),
});
export const Timestamp = IDL.Nat;
export const ConcernStatus = IDL.Variant({
  'notReceived' : IDL.Null,
  'damage' : IDL.Null,
  'expired' : IDL.Null,
  'short' : IDL.Null,
  'spoiled' : IDL.Null,
  'received' : IDL.Null,
});
export const ConcernItemStatus = IDL.Record({
  'status' : ConcernStatus,
  'receivedQty' : IDL.Opt(IDL.Float64),
  'itemName' : IDL.Text,
  'orderQty' : IDL.Float64,
});
export const ConcernRecord = IDL.Record({
  'confirmedAt' : IDL.Nat,
  'confirmedBy' : IDL.Text,
  'itemStatuses' : IDL.Vec(ConcernItemStatus),
  'orderId' : IDL.Nat,
  'restaurantName' : IDL.Text,
});
export const DailyRecord = IDL.Record({
  'meals' : IDL.Vec(Meal),
  'restaurantName' : IDL.Text,
  'timestamp' : Timestamp,
});
export const MasterCategory = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
});
export const RawMaterial = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'category' : IDL.Text,
});
export const RestaurantAssignment = IDL.Record({
  'allowedItems' : IDL.Vec(IDL.Text),
  'allowedCategories' : IDL.Vec(IDL.Text),
  'restaurantName' : IDL.Text,
});
export const Restaurant = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const RestaurantUser = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'restaurantName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([IDL.Text], [], []),
  'addDailyRecord' : IDL.Func(
      [IDL.Vec(Meal), Timestamp, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addRawMaterial' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addRestaurant' : IDL.Func([IDL.Text], [], []),
  'addUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteRawMaterial' : IDL.Func([IDL.Text], [], []),
  'deleteRestaurant' : IDL.Func([IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'getAllCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'name' : IDL.Text }))],
      ['query'],
    ),
  'getAllConcernRecords' : IDL.Func([], [IDL.Vec(ConcernRecord)], ['query']),
  'getAllDailyRecords' : IDL.Func([], [IDL.Vec(DailyRecord)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(MasterCategory)], ['query']),
  'getConcernRecord' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(ConcernRecord)],
      ['query'],
    ),
  'getIngredientsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Record({ 'name' : IDL.Text, 'category' : IDL.Text }))],
      ['query'],
    ),
  'getRawMaterials' : IDL.Func([], [IDL.Vec(RawMaterial)], ['query']),
  'getRawMaterialsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RawMaterial)],
      ['query'],
    ),
  'getRestaurantAssignment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RestaurantAssignment)],
      ['query'],
    ),
  'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(RestaurantUser)], ['query']),
  'resetToDefaultCredentials' : IDL.Func([], [], []),
  'saveConcernRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(ConcernItemStatus), IDL.Text],
      [],
      [],
    ),
  'seedDefaultData' : IDL.Func([], [], []),
  'setAdminPassword' : IDL.Func([IDL.Text], [], []),
  'setRestaurantAssignment' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateRawMaterial' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateRestaurant' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'verifyUserLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryName = IDL.Text;
  const Ingredient = IDL.Record({
    'name' : IDL.Text,
    'category' : CategoryName,
  });
  const Meal = IDL.Record({
    'name' : IDL.Text,
    'ingredients' : IDL.Vec(Ingredient),
  });
  const Timestamp = IDL.Nat;
  const ConcernStatus = IDL.Variant({
    'notReceived' : IDL.Null,
    'damage' : IDL.Null,
    'expired' : IDL.Null,
    'short' : IDL.Null,
    'spoiled' : IDL.Null,
    'received' : IDL.Null,
  });
  const ConcernItemStatus = IDL.Record({
    'status' : ConcernStatus,
    'receivedQty' : IDL.Opt(IDL.Float64),
    'itemName' : IDL.Text,
    'orderQty' : IDL.Float64,
  });
  const ConcernRecord = IDL.Record({
    'confirmedAt' : IDL.Nat,
    'confirmedBy' : IDL.Text,
    'itemStatuses' : IDL.Vec(ConcernItemStatus),
    'orderId' : IDL.Nat,
    'restaurantName' : IDL.Text,
  });
  const DailyRecord = IDL.Record({
    'meals' : IDL.Vec(Meal),
    'restaurantName' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const MasterCategory = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const RawMaterial = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'category' : IDL.Text,
  });
  const RestaurantAssignment = IDL.Record({
    'allowedItems' : IDL.Vec(IDL.Text),
    'allowedCategories' : IDL.Vec(IDL.Text),
    'restaurantName' : IDL.Text,
  });
  const Restaurant = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const RestaurantUser = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'restaurantName' : IDL.Text,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([IDL.Text], [], []),
    'addDailyRecord' : IDL.Func(
        [IDL.Vec(Meal), Timestamp, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addRawMaterial' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addRestaurant' : IDL.Func([IDL.Text], [], []),
    'addUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteRawMaterial' : IDL.Func([IDL.Text], [], []),
    'deleteRestaurant' : IDL.Func([IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'getAllCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'name' : IDL.Text }))],
        ['query'],
      ),
    'getAllConcernRecords' : IDL.Func([], [IDL.Vec(ConcernRecord)], ['query']),
    'getAllDailyRecords' : IDL.Func([], [IDL.Vec(DailyRecord)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(MasterCategory)], ['query']),
    'getConcernRecord' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(ConcernRecord)],
        ['query'],
      ),
    'getIngredientsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Record({ 'name' : IDL.Text, 'category' : IDL.Text }))],
        ['query'],
      ),
    'getRawMaterials' : IDL.Func([], [IDL.Vec(RawMaterial)], ['query']),
    'getRawMaterialsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RawMaterial)],
        ['query'],
      ),
    'getRestaurantAssignment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RestaurantAssignment)],
        ['query'],
      ),
    'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(RestaurantUser)], ['query']),
    'resetToDefaultCredentials' : IDL.Func([], [], []),
    'saveConcernRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(ConcernItemStatus), IDL.Text],
        [],
        [],
      ),
    'seedDefaultData' : IDL.Func([], [], []),
    'setAdminPassword' : IDL.Func([IDL.Text], [], []),
    'setRestaurantAssignment' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateRawMaterial' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateRestaurant' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'verifyUserLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };