/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryName = IDL.Text;
export const Ingredient = IDL.Record({
  'name' : IDL.Text,
  'category' : CategoryName,
});
export const Meal = IDL.Record({
  'name' : IDL.Text,
  'ingredients' : IDL.Vec(Ingredient),
});
export const Timestamp = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({ 'name' : CategoryName });
export const DailyRecord = IDL.Record({
  'meals' : IDL.Vec(Meal),
  'restaurantName' : IDL.Text,
  'timestamp' : Timestamp,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'restaurantName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDailyRecord' : IDL.Func(
      [IDL.Vec(Meal), Timestamp, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllDailyRecords' : IDL.Func([], [IDL.Vec(DailyRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoriesByType' : IDL.Func([IDL.Text], [IDL.Vec(Category)], ['query']),
  'getIngredientsByCategory' : IDL.Func(
      [CategoryName],
      [IDL.Vec(Ingredient)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryName = IDL.Text;
  const Ingredient = IDL.Record({
    'name' : IDL.Text,
    'category' : CategoryName,
  });
  const Meal = IDL.Record({
    'name' : IDL.Text,
    'ingredients' : IDL.Vec(Ingredient),
  });
  const Timestamp = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({ 'name' : CategoryName });
  const DailyRecord = IDL.Record({
    'meals' : IDL.Vec(Meal),
    'restaurantName' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'restaurantName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDailyRecord' : IDL.Func(
        [IDL.Vec(Meal), Timestamp, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllDailyRecords' : IDL.Func([], [IDL.Vec(DailyRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoriesByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Category)],
        ['query'],
      ),
    'getIngredientsByCategory' : IDL.Func(
        [CategoryName],
        [IDL.Vec(Ingredient)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };