/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Meal {
    name: string;
    ingredients: Array<Ingredient>;
}
export interface MasterCategory {
    id: string;
    name: string;
}
export type Timestamp = bigint;
export interface RestaurantUser {
    username: string;
    password: string;
    restaurantName: string;
}
export interface RawMaterial {
    id: string;
    name: string;
    category: string;
}
export interface Ingredient {
    name: string;
    category: CategoryName;
}
export interface ConcernRecord {
    confirmedAt: bigint;
    confirmedBy: string;
    itemStatuses: Array<ConcernItemStatus>;
    orderId: bigint;
    restaurantName: string;
}
export interface ConcernItemStatus {
    status: ConcernStatus;
    receivedQty?: number;
    itemName: string;
    orderQty: number;
}
export type CategoryName = string;
export interface RestaurantAssignment {
    allowedItems: Array<string>;
    allowedCategories: Array<string>;
    restaurantName: string;
}
export interface DailyRecord {
    meals: Array<Meal>;
    restaurantName: string;
    timestamp: Timestamp;
}
export interface Restaurant {
    id: string;
    name: string;
}
export enum ConcernStatus {
    notReceived = "notReceived",
    damage = "damage",
    expired = "expired",
    short_ = "short",
    spoiled = "spoiled",
    received = "received"
}
export interface backendInterface {
    addCategory(name: string): Promise<void>;
    addDailyRecord(meals: Array<Meal>, timestamp: Timestamp, restaurantName: string): Promise<bigint>;
    addRawMaterial(name: string, category: string): Promise<void>;
    addRestaurant(name: string): Promise<void>;
    addUser(username: string, password: string, restaurantName: string): Promise<void>;
    deleteCategory(id: string): Promise<void>;
    deleteRawMaterial(id: string): Promise<void>;
    deleteRestaurant(id: string): Promise<void>;
    deleteUser(username: string): Promise<void>;
    getAllCategories(): Promise<Array<{
        name: string;
    }>>;
    /**
     * / Retrieve all stored concern records (for admin / reporting).
     */
    getAllConcernRecords(): Promise<Array<ConcernRecord>>;
    getAllDailyRecords(): Promise<Array<DailyRecord>>;
    getCategories(): Promise<Array<MasterCategory>>;
    /**
     * / Retrieve the confirmed concern record for a specific order, if any.
     */
    getConcernRecord(orderId: bigint, restaurantName: string): Promise<ConcernRecord | null>;
    getIngredientsByCategory(cat: string): Promise<Array<{
        name: string;
        category: string;
    }>>;
    getRawMaterials(): Promise<Array<RawMaterial>>;
    getRawMaterialsByCategory(cat: string): Promise<Array<RawMaterial>>;
    getRestaurantAssignment(restaurantName: string): Promise<RestaurantAssignment | null>;
    getRestaurants(): Promise<Array<Restaurant>>;
    getUsers(): Promise<Array<RestaurantUser>>;
    resetToDefaultCredentials(): Promise<void>;
    /**
     * / Save concern statuses for an order. Once saved, the record is permanently
     * / stored on-chain and visible to all users. Subsequent calls for the same
     * / (orderId, restaurantName) are silently ignored to enforce immutability.
     */
    saveConcernRecord(orderId: bigint, restaurantName: string, itemStatuses: Array<ConcernItemStatus>, confirmedBy: string): Promise<void>;
    seedDefaultData(): Promise<void>;
    setAdminPassword(newPwd: string): Promise<void>;
    setRestaurantAssignment(restaurantName: string, allowedCategories: Array<string>, allowedItems: Array<string>): Promise<void>;
    updateCategory(id: string, name: string): Promise<void>;
    updateRawMaterial(id: string, name: string, category: string): Promise<void>;
    updateRestaurant(id: string, name: string): Promise<void>;
    updateUser(username: string, password: string, restaurantName: string): Promise<void>;
    verifyAdminPassword(pwd: string): Promise<boolean>;
    verifyUserLogin(username: string, password: string): Promise<string | null>;
}
import type { ConcernItemStatus as _ConcernItemStatus, ConcernRecord as _ConcernRecord, ConcernStatus as _ConcernStatus, RestaurantAssignment as _RestaurantAssignment } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0);
            return result;
        }
    }
    async addDailyRecord(arg0: Array<Meal>, arg1: Timestamp, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async addRawMaterial(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRawMaterial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRawMaterial(arg0, arg1);
            return result;
        }
    }
    async addRestaurant(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRestaurant(arg0);
            return result;
        }
    }
    async addUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteRawMaterial(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRawMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRawMaterial(arg0);
            return result;
        }
    }
    async deleteRestaurant(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRestaurant(arg0);
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getAllCategories(): Promise<Array<{
        name: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllConcernRecords(): Promise<Array<ConcernRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllConcernRecords();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllConcernRecords();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDailyRecords(): Promise<Array<DailyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDailyRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDailyRecords();
            return result;
        }
    }
    async getCategories(): Promise<Array<MasterCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getConcernRecord(arg0: bigint, arg1: string): Promise<ConcernRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConcernRecord(arg0, arg1);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConcernRecord(arg0, arg1);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIngredientsByCategory(arg0: string): Promise<Array<{
        name: string;
        category: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIngredientsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIngredientsByCategory(arg0);
            return result;
        }
    }
    async getRawMaterials(): Promise<Array<RawMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRawMaterials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRawMaterials();
            return result;
        }
    }
    async getRawMaterialsByCategory(arg0: string): Promise<Array<RawMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRawMaterialsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRawMaterialsByCategory(arg0);
            return result;
        }
    }
    async getRestaurantAssignment(arg0: string): Promise<RestaurantAssignment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantAssignment(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantAssignment(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurants();
            return result;
        }
    }
    async getUsers(): Promise<Array<RestaurantUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return result;
        }
    }
    async resetToDefaultCredentials(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetToDefaultCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetToDefaultCredentials();
            return result;
        }
    }
    async saveConcernRecord(arg0: bigint, arg1: string, arg2: Array<ConcernItemStatus>, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveConcernRecord(arg0, arg1, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveConcernRecord(arg0, arg1, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async seedDefaultData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDefaultData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDefaultData();
            return result;
        }
    }
    async setAdminPassword(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPassword(arg0);
            return result;
        }
    }
    async setRestaurantAssignment(arg0: string, arg1: Array<string>, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRestaurantAssignment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRestaurantAssignment(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCategory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
    async updateRawMaterial(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRawMaterial(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRawMaterial(arg0, arg1, arg2);
            return result;
        }
    }
    async updateRestaurant(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRestaurant(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRestaurant(arg0, arg1);
            return result;
        }
    }
    async updateUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2);
            return result;
        }
    }
    async verifyAdminPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPassword(arg0);
            return result;
        }
    }
    async verifyUserLogin(arg0: string, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyUserLogin(arg0, arg1);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyUserLogin(arg0, arg1);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ConcernItemStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConcernItemStatus): ConcernItemStatus {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ConcernRecord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConcernRecord): ConcernRecord {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ConcernStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConcernStatus): ConcernStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ConcernRecord]): ConcernRecord | null {
    return value.length === 0 ? null : from_candid_ConcernRecord_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantAssignment]): RestaurantAssignment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    confirmedAt: bigint;
    confirmedBy: string;
    itemStatuses: Array<_ConcernItemStatus>;
    orderId: bigint;
    restaurantName: string;
}): {
    confirmedAt: bigint;
    confirmedBy: string;
    itemStatuses: Array<ConcernItemStatus>;
    orderId: bigint;
    restaurantName: string;
} {
    return {
        confirmedAt: value.confirmedAt,
        confirmedBy: value.confirmedBy,
        itemStatuses: from_candid_vec_n4(_uploadFile, _downloadFile, value.itemStatuses),
        orderId: value.orderId,
        restaurantName: value.restaurantName
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ConcernStatus;
    receivedQty: [] | [number];
    itemName: string;
    orderQty: number;
}): {
    status: ConcernStatus;
    receivedQty?: number;
    itemName: string;
    orderQty: number;
} {
    return {
        status: from_candid_ConcernStatus_n7(_uploadFile, _downloadFile, value.status),
        receivedQty: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.receivedQty)),
        itemName: value.itemName,
        orderQty: value.orderQty
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notReceived: null;
} | {
    damage: null;
} | {
    expired: null;
} | {
    short: null;
} | {
    spoiled: null;
} | {
    received: null;
}): ConcernStatus {
    return "notReceived" in value ? ConcernStatus.notReceived : "damage" in value ? ConcernStatus.damage : "expired" in value ? ConcernStatus.expired : "short" in value ? ConcernStatus.short : "spoiled" in value ? ConcernStatus.spoiled : "received" in value ? ConcernStatus.received : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConcernRecord>): Array<ConcernRecord> {
    return value.map((x)=>from_candid_ConcernRecord_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConcernItemStatus>): Array<ConcernItemStatus> {
    return value.map((x)=>from_candid_ConcernItemStatus_n5(_uploadFile, _downloadFile, x));
}
function to_candid_ConcernItemStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConcernItemStatus): _ConcernItemStatus {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ConcernStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConcernStatus): _ConcernStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ConcernStatus;
    receivedQty?: number;
    itemName: string;
    orderQty: number;
}): {
    status: _ConcernStatus;
    receivedQty: [] | [number];
    itemName: string;
    orderQty: number;
} {
    return {
        status: to_candid_ConcernStatus_n15(_uploadFile, _downloadFile, value.status),
        receivedQty: value.receivedQty ? candid_some(value.receivedQty) : candid_none(),
        itemName: value.itemName,
        orderQty: value.orderQty
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConcernStatus): {
    notReceived: null;
} | {
    damage: null;
} | {
    expired: null;
} | {
    short: null;
} | {
    spoiled: null;
} | {
    received: null;
} {
    return value == ConcernStatus.notReceived ? {
        notReceived: null
    } : value == ConcernStatus.damage ? {
        damage: null
    } : value == ConcernStatus.expired ? {
        expired: null
    } : value == ConcernStatus.short ? {
        short_: null
    } : value == ConcernStatus.spoiled ? {
        spoiled: null
    } : value == ConcernStatus.received ? {
        received: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ConcernItemStatus>): Array<_ConcernItemStatus> {
    return value.map((x)=>to_candid_ConcernItemStatus_n13(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
